version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '${PORT}:5432'
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
    volumes:
      - ./dados:/dados
      - polls_pg_data:/bitnami/postgresql
volumes:
  
  polls_pg_data: