version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    env_file:
      - .env
    ports:
      - '${PORT}:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_PASSWORD}
    volumes:
      - ./dados:/dados
      - ${VOLUME}:/bitnami/postgresql
volumes:
 ${VOLUME}: